# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelScoreChange',
            fields=[
                ('forecast_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score_change', serialize=False, to='forecast_app.ForecastModel')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='step_ahead_increment',
            field=models.IntegerField(default=0, help_text="Optional field that's required when Target.is_step_ahead is True, is an integer specifying how many time steps ahead the Target is. Can be negative, zero, or positive."),
        ),
    ]
