# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodel',
            name='abbreviation',
            field=models.TextField(default='', help_text="Short name for the model. Used in the 'model' column in downloaded CSV score files."),
            preserve_default=False,
        ),
    ]
