# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0002_quantiledistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='notes',
            field=models.TextField(blank=True, help_text='Text describing anything slightly different about a given forecast, e.g., a changed set of assumptions or a comment about when the forecast was created. Notes should be brief, typically less than 50 words.', null=True),
        ),
    ]
