# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='truth_updated_at',
            field=models.DateTimeField(blank=True, help_text='The last time the truth was updated.', null=True),
        ),
    ]
