# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0006_model_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'CLOUD_FILE_UPLOADED'), (2, 'QUEUED'), (3, 'CLOUD_FILE_DOWNLOADED'), (4, 'SUCCESS'), (5, 'FAILED'), (6, 'TIMEOUT')], default=0),
        ),
    ]
