# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0007_job_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMetaPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_count', models.IntegerField(default=None, null=True)),
                ('named_count', models.IntegerField(default=None, null=True)),
                ('bin_count', models.IntegerField(default=None, null=True)),
                ('sample_count', models.IntegerField(default=None, null=True)),
                ('quantile_count', models.IntegerField(default=None, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.Forecast')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastMetaTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.Forecast')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.Target')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastMetaUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.Forecast')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
