# Generated by Django 2.2.15 on 2020-09-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0007_job_timeout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreCsvFileCache',
        ),
    ]
