# Generated by Django 2.2.15 on 2020-10-29 15:11

import django.utils.timezone
from django.db import migrations, models


#
# This file does both schema and data migrations for the new `Forecast.issue_date` field, and was created manually to do
# so. There are three operations:
#
# 1. Add the field with an arbitrary default so that existing rows are filled. Recall that The field is null=False - the
#    DateField default.
# 2. Correct existing rows' `issue_date` values to be the date portion of each row's `created_at` value.
# 3. Alter the field to remove the default.
#

def forwards_func(apps, schema_editor):
    # via https://docs.djangoproject.com/en/2.2/ref/migration-operations/#runpython : We get the model from the
    # versioned app registry; if we directly import it, it'll be the wrong version:
    Forecast = apps.get_model("forecast_app", "Forecast")

    # this is the slow one-at-a-time approach. I tried using https://docs.djangoproject.com/en/2.2/ref/models/expressions/#f-expressions
    # but was too complicated
    for forecast in Forecast.objects.all().iterator():
        forecast.issue_date = forecast.created_at.date()
        forecast.save()


class Migration(migrations.Migration):
    dependencies = [
        ('forecast_app', '0009_forecast_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='issue_date',
            # 1/3 add field. nullable for existing rows. arbitrary default. corrected next
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('forecast_model', 'time_zero', 'issue_date'),
                                               name='unique_version'),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),  # 2/3 set value for existing rows
        migrations.AlterField(  # 3/3 make field non-nullable
            model_name='forecast',
            name='issue_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
