# Generated by Django 2.2.15 on 2020-12-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0010_forecast_issue_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RowCountCache',
        ),
    ]
