# Generated by Django 2.2.15 on 2020-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0011_delete_rowcountcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodel',
            name='is_oracle',
            field=models.BooleanField(default=False, help_text='True if this model acts as a truth oracle.'),
        ),
        migrations.DeleteModel(
            name='TruthData',
        ),
    ]
