# Generated by Django 2.2.15 on 2020-12-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0012_truth_as_forecasts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelastupdate',
            name='forecast_model',
        ),
        migrations.RemoveField(
            model_name='scorelastupdate',
            name='score',
        ),
        migrations.RemoveField(
            model_name='scorevalue',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='scorevalue',
            name='score',
        ),
        migrations.RemoveField(
            model_name='scorevalue',
            name='target',
        ),
        migrations.RemoveField(
            model_name='scorevalue',
            name='unit',
        ),
        migrations.AlterField(
            model_name='forecastmodel',
            name='abbreviation',
            field=models.TextField(help_text='Short name for the model in 15 alphanumeric characters or less.'),
        ),
        migrations.DeleteModel(
            name='ModelScoreChange',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='ScoreLastUpdate',
        ),
        migrations.DeleteModel(
            name='ScoreValue',
        ),
    ]
