# Generated by Django 3.1.7 on 2021-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0015_predictionelement_2_of_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
