# Generated by Django 3.1.12 on 2021-11-03 20:18

from django.db import migrations, models


#
# This file does both schema and data migrations for the issue [change Target fields to support visualization #328]. I
# edited the Django-generated file to get this. We change the default value of `Target.reference_date_type` from None to
# the arbitrary Target.DAY_RDT for Targets where Target.is_step_ahead=True so that serialized Targets are valid. (This
# is important when editing a Project via a project config JSON file, which is what we do after this migration.)
#

def forwards_func(apps, schema_editor):
    # via https://docs.djangoproject.com/en/2.2/ref/migration-operations/#runpython : We get the model from the
    # versioned app registry; if we directly import it, it'll be the wrong version:
    Target = apps.get_model("forecast_app", "Target")

    # this is the slow one-at-a-time approach. I tried using https://docs.djangoproject.com/en/2.2/ref/models/expressions/#f-expressions
    # but was too complicated
    for target in Target.objects.all().iterator():
        if target.is_step_ahead:
            target.reference_date_type = 0  # Target.DAY_RDT
            target.save()


class Migration(migrations.Migration):
    dependencies = [
        ('forecast_app', '0019_forecast_model_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='unit',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='step_ahead_increment',
            new_name='numeric_horizon',
        ),
        migrations.AddField(
            model_name='target',
            name='outcome_variable',
            field=models.TextField(default='',
                                   help_text="Human-readable string naming the target variable, e.g. 'Incident cases'."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='reference_date_type',
            field=models.IntegerField(
                choices=[(0, 'DAY'), (1, 'MMWR_WEEK_LAST_TIMEZERO_MONDAY'), (2, 'MMWR_WEEK_LAST_TIMEZERO_TUESDAY'),
                         (3, 'BIWEEK')],
                help_text='Indicates how the Target calculates reference_date and target_end_date from a TimeZero. It is required if `is_step_ahead` is True.',
                null=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
