# Generated by Django 3.1.13 on 2022-07-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0020_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='visualization_y_label',
        ),
    ]
