# Generated by Django 3.1.13 on 2022-07-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0021_remove_project_visualization_y_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time_interval_type',
        ),
    ]
