# Generated by Django 3.1.13 on 2022-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0022_remove_project_time_interval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='viz_options',
            field=models.JSONField(blank=True, help_text='Optional object containing options to pass to zoltar_viz.js', null=True),
        ),
    ]
