# Generated by Django 3.1.13 on 2022-12-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0023_project_viz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='pred_ele',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pred_data', serialize=False, to='forecast_app.predictionelement'),
        ),
        migrations.AlterField(
            model_name='targetcat',
            name='cat_b',
            field=models.BooleanField(null=True),
        ),
    ]
