# Generated by Django 4.1.10 on 2024-03-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0024_fix_model_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmetaprediction',
            name='mean_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastmetaprediction',
            name='median_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastmetaprediction',
            name='mode_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastmetaprediction',
            name='bin_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastmetaprediction',
            name='named_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastmetaprediction',
            name='point_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastmetaprediction',
            name='quantile_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastmetaprediction',
            name='sample_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionelement',
            name='pred_class',
            field=models.IntegerField(choices=[(0, 'bin'), (1, 'named'), (2, 'point'), (3, 'sample'), (4, 'quantile'), (5, 'mean'), (6, 'median'), (7, 'mode')]),
        ),
        migrations.AlterField(
            model_name='target',
            name='reference_date_type',
            field=models.IntegerField(choices=[(0, 'DAY'), (1, 'MMWR_WEEK_LAST_TIMEZERO_MONDAY'), (2, 'MMWR_WEEK_LAST_TIMEZERO_TUESDAY'), (3, 'BIWEEK'), (4, 'MMWR_WEEK_LAST_TIMEZERO_SATURDAY')], help_text='Indicates how the Target calculates reference_date and target_end_date from a TimeZero. It is required if `is_step_ahead` is True.', null=True),
        ),
    ]
